### ISSUE TITLE
Time interval selection control component

### ISSUE THREAD

**Issue by daebwae** [rfcx/web-components#11]
Frank - a senior forest ranger - has the responsibility to plan when to send other rangers into the field. He wants to scroll through the events on the map that happend in the last day or last week. This way, Frank can get a better idea on how events change over time and plan better ahead on when to send rangers into the field. 

To help Frank, we create a new time interval selection control, that looks like this: 
![image](https://cloud.githubusercontent.com/assets/749854/17622194/0b37c494-6099-11e6-8409-4afe664e37e0.png)

The whole component is a `timeline` which has a beginning (leftmost point) and end (rightmost point). The blue region is called the `selected time` which can be dragged wihthin the timeline to select the right beginning and end to display on the map. Also user can click on any interval's edge (left or right), drag mouse and increase/decrease interval's value. Think of the whole timeline like a scrollbar and the selected time as the scroll bar's "scroller". The vertical bars that represent the times are called "ticks" in this task. 

The code to generate this component is: 

`<rfcx-time-interval-selection begin="2016-08-12T18:00:00Z" end="2016-08-13T04:00:00Z" interval="1h" selected-begin="2016-08-12T20:00:00Z" selected-end="2016-08-12T21:00:00Z"></rfcx-time-interval-selection>`

The component has the following _required inputs_: 
1. begin: an ISO 8601 string, it's the leftmost part of timeline, here: 2016-08-12T18:00:00Z
2. end: an ISO 8601 string, it's the rightmost part of timeline, here: 2016-08-13T04:00:00Z
3. interval: the width of the `selected time`; we can use https://github.com/mobz/date-range-parser for this to parse the range, here "1h

The component has the following _optional inputs_:
1. timeline-color: a hexcode color for the background of the time line; default: #b8e986
2. selected-color: a hexcode color for the background of the selected time scroller; default: #4a90e2
3. ticks-color: a hexcode color for the background of the vertical lines i.e. ticks that represent a time: default: #bfbfbf
4. labels-color: a hexcode color for ticks labels: default: #4f90e2
5. timeFormat: moment.js compatible -  http://momentjs.com/docs/#/displaying/format/ formatted time string; default: "HH:mm"

The component has the following _outputs_ which are automatically updated when the user drags the selected time: 
1. selected-begin: an ISO 8601 string, it's the leftmost part of timeline, here: 2016-08-12T20:00:00Z
2. selected-end: an ISO 8601 string, it's the rightmost part of timeline, here: 2016-08-12T21:00:00Z

Here are a few more images that help to visualize the different settings of the scroll bar: 

![image](https://cloud.githubusercontent.com/assets/749854/17622201/168421ee-6099-11e6-999f-f123bcf13231.png)

![image](https://cloud.githubusercontent.com/assets/749854/17622206/1c556722-6099-11e6-94ec-8d29c7fb180e.png)

![image](https://cloud.githubusercontent.com/assets/749854/17622208/2417d152-6099-11e6-8524-9ab725cf09cd.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/167270113296773/167313494637300)

**Comment by daebwae** [comment]
Just to test integration

**Comment by rassokhin-s** [comment]
The following improvements were implemented:
- widget watches for changes in `begin`, `end` and `interval` attributes changes and automatically refreshes timeline
- when user has changed value of timeline (dragged a range or updated size of range) then directive sends an event `rfcx-time-interval-selection_interval-changed` event - then you can watch for this event instead of watching for each `begin` and `end` variables.
- directive automatically generates 11 tick lines, but when widget's container size is less then 400px, directive hides half of ticks labels.
